### ISSUE TITLE
Forum: titel van comments

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#100]
Bij een comment op een post gebruikt hij de eerste paar woorden als titel, erg lelijk, zie afbeelding:

![image](https://user-images.githubusercontent.com/30278588/30385620-06b0e85e-98a8-11e7-9f22-678fa998fafa.png)

**Comment by lesteenman** [comment]
Dit is op het forum inderdaad - bij andere posts ben ik er al mee bezig (geweest? Weet niet eens meer zeker).

**Comment by PauluzzS** [comment]
Andere posts had je reeds opgelost, meen ik. Dat stuurde je nog op telegram.

**Comment by lesteenman** [comment]
Bon, thanks for the reminder.
