### ISSUE TITLE
Submenu niet in het midden

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#101]
Zou het submenu naar het midden kunnen worden verplaats in plaats van half rechts?

**Comment by lesteenman** [comment]
Dat is juist bewust rechts gezet voor #39. Nu is het submenu aligned (rechts) met zowel het main menu als met de content.

**Comment by Maharball1** [comment]
Ok, valid point! Al vind ik het op de startpagina wel wat minder mooi, aangezien daar een groot logo in het midden uitgelijnd staat. Wellicht daar wel in het midden?

**Comment by lesteenman** [comment]
Dat is misschien nog wel een aardig idee inderdaad - daar heb je ook minder
vaak content die tot aan rechts komt, geloof ik.

**Comment by Maharball1** [comment]
Dan mag de wontfix er ook vanaf voor de homepage.

**Comment by jpingen** [comment]
-1 voor de inconsistentie die dat creëert.

**Comment by lesteenman** [comment]
Al staat die menubalk daar toch al een stuk lager. Misschien is links uitlijnen op de voorpagina, rechts op andere pagina's een idee? Dan is het aligned met de content/menu waar hij verder het dichtst bij staat.

**Comment by PauluzzS** [comment]
Het is toch al inconsistent. Ik geef daarom geen fucks

Groet,

Paul L. Smits

**Comment by Maharball1** [comment]
@lesteenman Lijkt me een goede oplossing! Doe maar.

**Comment by lesteenman** [comment]
Als experiment even gedaan. Hoor graag de meningen ;)

**Comment by Maharball1** [comment]
@lesteenman dit is niet het midden, maar links uitgelijnd. 
![image](https://user-images.githubusercontent.com/30278588/30419852-1e6eb6e8-9938-11e7-8431-9054ff9e1561.png)

**Comment by PauluzzS** [comment]
Dat leek je 10 uur geleden nog een goede oplossing @Maharball1

**Comment by Maharball1** [comment]
Ooh fuck, ik bedoelde natuurlijk midden! Dacht dat Erik dat bedoelde....

2017-09-14 10:34 GMT+02:00 Paul S <notifications@github.com>:

**Comment by jpingen** [comment]
Zoals het er nu staat word ik er wel erg autistisch van....

![image](https://user-images.githubusercontent.com/16253465/30422591-b6a1e9dc-9940-11e7-90d3-e41e11585511.png)

**Comment by Maharball1** [comment]
Ja, Erik, zet hem eens even in het midden. Dan geef ik ook even mijn
feedback op die setting.

2017-09-14 11:35 GMT+02:00 jpingen <notifications@github.com>:

**Comment by PauluzzS** [comment]
Kun je ook zelf even doen in je browser:
![image](https://user-images.githubusercontent.com/15788026/30423787-381118d2-9944-11e7-92d7-68b9b63a43aa.png)
beter dan links, maar m.i. niet beter dan rechts.

**Comment by Maharball1** [comment]
Mm....wellicht alles in het midden dan op de frontpage?! :P

2017-09-14 12:00 GMT+02:00 Paul S <notifications@github.com>:

**Comment by lesteenman** [comment]
Nooope, tegen. Links vond ik nog wel aardig omdat het dan weer uitgelijnd is met de rest van de content, waar het vlak boven staat. Midden vind ik idd ook wel enorm anti-consistent. Dan ga ik liever weer voor rechts.
