### ISSUE TITLE
Aantal comments zichtbaar voor externen 

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#102]
Als je niet ingelogd bent zie je op de homepage onder elk nieuwsbericht staan hoeveel comments er zijn, echter heb je niet het recht deze comments te lezen.

Lijkt me ook niet nodig dat externen zien hoe actief (of juist niet actief) onze site gebruikt wordt ;)

**Comment by PauluzzS** [comment]
Of we maken er fictieve nummers van die veel hoger oplopen dan de
daadwerkelijke hoeveelheid comments. Beetje bluffen 😁

Groet,

Paul L. Smits

2017-09-13 20:34 GMT+02:00 jpingen <notifications@github.com>:
