### ISSUE TITLE
Missende dagen bij activiteiten, uitschrijven maanden

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#103]
Ik zie graag als je op activiteiten klikt niet Sep, of Okt staan, ik zie daar graag de maanden uitgeschreven staan, evenals uitgeschreven dagen, dus iets als in woensdag 1 september 2017 2030 uur

**Comment by jpingen** [comment]
Goed idee, op voorwaarde dat daarmee niet alle activiteiten twee regels gaan beslaan (zie onderstaande afbeelding), dat maakt het overzicht alleen maar minder duidelijk naar mijn mening.

![image](https://user-images.githubusercontent.com/16253465/30398348-56b0c4a0-98d0-11e7-8193-381697b756b5.png)

**Comment by Maharball1** [comment]
Maken de tabel wat breder overal?

**Comment by lesteenman** [comment]
Zelfs op smalle schermen en telefoons? Het is waarschijnlijk te doen om te switchen van format wanneer je naar smallere schermen gaat, maar dat is relatief veel moeite. Komt wel een keertje. Voorlopig wordt het op smallere schermen heel lelijk, en wordt het er niet minder duidelijk van imo.

**Comment by Maharball1** [comment]
Ik vind het vervelend in het overzicht in ieder geval de dagen niet te zien.

Op 13 sep. 2017 22:33 schreef "Erik" <notifications@github.com>:

**Comment by jpingen** [comment]
Dan prefereer ik overzichtelijkheid boven volledig uitgeschreven data.

**Comment by lesteenman** [comment]
Hoe het er uit ziet met korte dagen er voor:
![capture1](https://user-images.githubusercontent.com/963290/30399541-4f39f06c-98d4-11e7-8e91-ada15e30a39f.png)

Hetzelfde, maar wat breder (werkt dus niet op smallere schermen, omdat het dan bijv. de titel verdrukt):
![capture2](https://user-images.githubusercontent.com/963290/30399542-4f404f02-98d4-11e7-9218-cb1ef022f657.PNG)

En ten slotte, als je alles uit gaat schrijven:
![capture3](https://user-images.githubusercontent.com/963290/30399540-4f390bca-98d4-11e7-8272-e1762d05b255.PNG)

Ik denk dat er een overzichtelijkere manier moet zijn om het te laten zien...

Meerdere regels werkt ook niet direct:
![capture4](https://user-images.githubusercontent.com/963290/30399631-9e74f78a-98d4-11e7-9cda-2b55dc178198.PNG)

**Comment by Maharball1** [comment]
De 1e manier kan ik wel goed handelen. Alleen datum en tijd Nederlands! :P

**Comment by jpingen** [comment]
Optie 1 & 2 lijken wel prima. Is er nog een mogelijkheid voor een divider tussen datum & tijd? Bijvoorbeeld 'Thu 14 Sep 2017 - 21:00'
