### ISSUE TITLE
Menu en content alignment verschuift bij praesidium en polls

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#108]
Alle paginae hebben dezelfde uitlijning horizontaal, behalve praesidium en polls.

**Comment by PauluzzS** [comment]
Ah, dit komt door de scroll-bar in de browser die op elke pagina behalve praesidium en polls aanwezig is. Is er iets aan te doen, of moet ik maar accepteren dat het menu steeds op een andere plek op m'n scherm staat?

**Comment by lesteenman** [comment]
Hmm, das irritant. Ik ga kijken of er wat aan te doen is, denk het wel.
