### ISSUE TITLE
Nested comments zijn niet responsive 

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#111]
Comments op mobiel gaan mis bij level 3:

![screenshot_20170914-164636](https://user-images.githubusercontent.com/16253465/30436697-1588983e-996d-11e7-9ae8-ca40332577ae.png)

**Comment by PauluzzS** [comment]
Gaat bij mij prima:
![image](https://user-images.githubusercontent.com/15788026/30437084-0e953e1e-996e-11e7-853b-ec61f5e88952.png)
