### ISSUE TITLE
Kan geen breaks maken in nieuwe editor

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#112]
mogelijk alleen bij objecten:
![image](https://user-images.githubusercontent.com/15788026/30505039-96ef5ba0-9a72-11e7-88c2-362b77d8969d.png)
p en br tags helpen iig niet.
![image](https://user-images.githubusercontent.com/15788026/30505055-abe57508-9a72-11e7-8c5d-d3ef8cc3cebd.png)

**Comment by lesteenman** [comment]
Huh. Dat is ook niet hoe die editor er uit hoort te zien... er lijkt iets niet geladen te zijn. Staan er errors in je javascript console (f12)?

Also, aangezien er aardig wat screenshots van interne content langs komen: Denk er aan dat deze Github publiek is. Inmiddels kan hij waarschijnlijk over naar privé, nu de drempel voor heeren om te joinen wat minder erg is.

**Comment by PauluzzS** [comment]
![image](https://user-images.githubusercontent.com/15788026/30505342-60d527be-9a74-11e7-9553-0cb365e830ea.png)

**Comment by PauluzzS** [comment]
Editor werkt voor mij bij nieuwsitems wel. Bij activiteiten, objecten niet.

**Comment by PauluzzS** [comment]
Gebrek aan breaks is wel storend om een leesbare reactie te maken:
![image](https://user-images.githubusercontent.com/15788026/30512694-27239f56-9af5-11e7-8f38-08fddf15b7ad.png)

**Comment by lesteenman** [comment]
Mhm. Ik hoop vanavond nog lang genoeg tijd te hebben om te kunnen zien
waarom dat mis gaat bij jou.

**Comment by lesteenman** [comment]
Fixed. Alleen bij polls kan het blijkbaar niet, aangezien deze een textveld ipv een text area als invoertype hebben. Dat wordt nog wat meer moeite om om te zetten, vrees ik.

**Comment by PauluzzS** [comment]
Oh well, polls moeten maar gewoon bondig ingeleid worden ;)

Groet,

Paul L. Smits
