### ISSUE TITLE
Profile pics bleed into comments

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#113]
Zie falco's post:
![image](https://user-images.githubusercontent.com/15788026/30511400-5321c5fa-9ad8-11e7-8f12-3e62cbf4517e.png)
from: https://pcsa-incognito.nl/node/22229

**Comment by lesteenman** [comment]
Ah, damn. Ik had geen rekening gehouden met Heeren die een super brede foto
gebruiken... Dat wordt op de Heeren pagina vast ook een pracht plaatje.
Binnenkort maar een foto cropper en deels verplichte verhoudingen
toevoegen.
