### ISSUE TITLE
Stange edge behaviour is strange

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#115]
![image](https://user-images.githubusercontent.com/15788026/30658720-f248606a-9e3b-11e7-8c87-ecd160cbfcfb.png)
Niet eerder gezien, maar vandaag is er een vreemd rood lijntje in edge. Verdwijnt overigens als men ergens op klikt.

**Comment by Maharball1** [comment]
Vandaag heb ik dat lijntje in ieder geval niet.
