### ISSUE TITLE
Menutekst in pagina terwijl menu gewoon zichtbaar is bij opgeven aanwezigheid activiteit

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#120]
Ik moest mijn beschikbaarheid aangeven en ik klikte op de activiteit (colloquium Ilia). Ik klikte op de edit-knop om iets te zien, klikte op save en daarna kwam dit tevoorschijn, een combinatie van het verplicht invullen van de aanwezigheid en de activiteit: 

![image](https://user-images.githubusercontent.com/30278588/30852237-62f5e062-a2ab-11e7-95ef-8dffca4f62ed.png)

**Comment by Maharball1** [comment]
Nu ik nog een keer kijk is die hele rotzooi automatisch in de beschrijving van de activiteit gekopieerd, dat is heel vreemd. Ik verwijder het nu, dan moet de activiteit weer goed zijn. Wellicht kan dit gereproduceerd worden? Zo niet, dan is het erg raar...

**Comment by lesteenman** [comment]
Ervoor zorgen dat bij het saven van de content er ook geen redirect komt vanuit de force activity reply module. Dit komt somehow in de body van de verstuurde content terecht, waardoor dit in de activiteit staat...

**Comment by lesteenman** [comment]
Hopelijk opgelost dat dit kan gebeuren.
