### ISSUE TITLE
Onbekend al meer dan 72 uur vantevoren niet meer mogelijk

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#121]
Ik wou mijn aanwezigheid bij het Colloquium van Ilia aanpassen van afwezig naar onbekend. Aangezien het nog meer dan 48 uur van tevoren is, zou dat moeten kunnen. Maar dat kon niet, ik werd gelijk doorverwezen naar de pagina om mijn aanwezigheid aan te passen naar aanwezig/afwezig.

**Comment by lesteenman** [comment]
Meer activiteiten waar dat atm nog gebeurt? Krijg het nu niet gereproduceerd.

**Comment by lesteenman** [comment]
Mogelijk per ongeluk gefixt, door de nieuwste versie die ik in dev had staan toch maar te pushen.

**Comment by Maharball1** [comment]
Ik heb het nog wel bij Kamp, waarschijnlijk omdat jij postactief bent en de
postactieve aanwezigheid nergens is aangevinkt ;)

2017-10-02 22:47 GMT+02:00 Erik <notifications@github.com>:

**Comment by lesteenman** [comment]
Nee, dat heb ik in m'n testomgeving getest door als actief te gaan staan ;)
Maar ik had een foutje gemaakt en alsnog de nieuwe changes niet binnen
gehaald. Nu nog steeds?

**Comment by Maharball1** [comment]
Nu niet, dus het lijkt te werken. We gaan het zien als ik morgen om 17:30
wel mijn beschikbaarheid moet invullen.

2017-10-03 9:38 GMT+02:00 Erik <notifications@github.com>:

> Nee, dat heb ik in m'n testomgeving getest door als actief te gaan staan ;)
> Maar ik had een foutje gemaakt en alsnog de nieuwe changes niet binnen
> gehaald. Nu nog steeds?
>
