### ISSUE TITLE
Menu verandert niet bij scrollen op homepage

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#123]
Zie:
![image](https://user-images.githubusercontent.com/16253465/30977148-fd24d3ba-a476-11e7-9b0a-85e0172ab2d2.png)

Menu zou kleiner moeten worden & een achtergrondkleur krijgen

**Comment by lesteenman** [comment]
Huh? Waar gebeurt dat? Bij mij werkt het hier..

**Comment by jpingen** [comment]
Op de homepage, is ook voor het eerst nu bij mij.  (hard) refresh hielp ook
niet.

**Comment by jpingen** [comment]
Nope, werkt nog steeds niet hier.

**Comment by lesteenman** [comment]
force-refresh gedaan?

**Comment by lesteenman** [comment]
Foutje, was alsnog vergeten de changes goed te pullen. Try again.

**Comment by jpingen** [comment]
Jep, gefixt! :)
