### ISSUE TITLE
Hover-effect secundaire navigatie

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#125]
De secundaire navigatie (rode balk) heeft nu geen hover effect. Graag een underline & eventueel fel wit als kleur bij hover :)

**Comment by lesteenman** [comment]
Prima, kan kijken of ik dat redelijk gelijk kan krijgen in stijl aan de main navigatie. Is de huidige secundaire navigatie wel redelijk OK verder?

Deels relevant, maar ik was er ook nog licht over aan het nadenken om de hoogte van de header image te verkleinen wanneer je bent ingelogd, zodat je nog wel een header image hebt, maar niet meer bijna pagina-vullend.

**Comment by jpingen** [comment]
> Prima, kan kijken of ik dat redelijk gelijk kan krijgen in stijl aan de main navigatie. Is de huidige secundaire navigatie wel redelijk OK verder?

Ja.

> Deels relevant, maar ik was er ook nog licht over aan het nadenken om de hoogte van de header image te verkleinen wanneer je bent ingelogd, zodat je nog wel een header image hebt, maar niet meer bijna pagina-vullend.

Na inlog lijkt me dat wel prima. Voor externen staat 't wel mooi :)
