### ISSUE TITLE
Opkomende en gebeurde activiteiten scheiden

### ISSUE THREAD

**Issue by lesteenman** [lesteenman/pcsa-drupal-theme#22]

**Comment by PauluzzS** [comment]
Willen we activiteit pas sluiten na eindtijd? Ik vind het soms wel frustrerend dat je niet meer op de site je aanwezigheid kan bijstellen als de starttijd verstreken is 👅

**Comment by lesteenman** [comment]
Momenteel kun je überhaupt altijd je aanwezigheid aanpassen, dat moet ook
nog even veranderen ;) zal daar zo een issue voor aanmaken.

**Comment by lesteenman** [comment]
Daarnaast het volgorde van de opkomende activiteiten omdraaien, zodat de eerstvolgende activiteit bovenaan staat.

**Comment by lesteenman** [comment]
Opties (hopelijk):

- Verschillende tabs/filters
- Blok met opkomende activiteiten bovenaan, daaronder 1 pagina aan afgelopen activiteiten. Verder terug scrollen in de pager geeft alleen nog maar afgelopen activiteiten.

**Comment by lesteenman** [comment]
Ok, niet de mooiste oplossing, maar het werkt. Boven- en onderaan de pagina 'activiteiten' staan nu links om te wisselen tussen archief en opkomend.
