### ISSUE TITLE
Show amount of comments on activity/comment

### ISSUE THREAD

**Issue by lesteenman** [lesteenman/pcsa-drupal-theme#23]

**Comment by PauluzzS** [comment]
+ unread comments bold?

**Comment by lesteenman** [comment]
Might partially be related to #8.

**Comment by lesteenman** [comment]
Possibly: https://drupal.stackexchange.com/a/233237/16330

**Comment by lesteenman** [comment]
Another possible example, both for this and for #8: https://drupal.stackexchange.com/questions/88529/how-to-create-a-view-of-unread-comments-on-own-nodes-for-the-users-profile-page
