### ISSUE TITLE
Improve comment formatting

### ISSUE THREAD

**Issue by lesteenman** [lesteenman/pcsa-drupal-theme#25]
- Add user avatars next to comments
- Remove 'new' word

**Comment by lesteenman** [comment]
Also change other styling for comments:
- Remove titles
- Make name of the user posting more clear (might not be too necessary when we have avatars)

**Comment by jpingen** [comment]
- Remove 'new' label, or change formatting

**Comment by PauluzzS** [comment]
Bij de polls is er in tegenstelling tot nieuws en activiteiten een comment-systeem waar je wel zelf je titel mag bepalen. Geeft ook wel een interessant effect: https://pcsa-incognito.nl/node/22633

**Comment by lesteenman** [comment]
Overigens was dat er ook bij nieuws en activiteiten maar heb ik die
verborgen. Ik weet niet zeker of 't mooi te krijgen is eigenlijk.. Zal 't
bij polls even zo laten ter vergelijking en bij nieuws en activiteiten
Pingen z'n ontwerp bouwen.
