### ISSUE TITLE
Betere oplossing voor menu's

### ISSUE THREAD

**Issue by lesteenman** [lesteenman/pcsa-drupal-theme#34]
Op dit moment hebben we een tweede menu dat alleen op de voorpagina zichtbaar is, en alleen verder naar beneden. Dit moet somehow gecombineerd kunnen.

**Comment by PauluzzS** [comment]
Moet makkelijker zijn om van Heerenlijst naar dispuutsobjecten te gaan et cetera. Tweede menu mag van mij permanent onder hoofdmenu geplakt worden op desktop.

**Comment by lesteenman** [comment]
Zorgt voor een flinke bak aan ruimtevulling bovenaan. Daarbij werkt dat voor mobiel voor geen meter. Somehow moeten die menu's gewoon gecombineerd worden.

In een eerdere versie van de site had ik overigens wel zo'n oplossing. 2 balken menu bovenin beeld, waarvan 1 kleiner weergegeven voor minder belangrijke items. Het mobiele menu is dan wel nog steeds een puntje.

We need a designer for this! @jpingen

**Comment by PauluzzS** [comment]
hamburger erbij? Twee kolommen in het hamburgermenu?

Sidenote: door op een leeg stuk menu te klikken kom ik in ieder geval wel direct bij de Heerenlijst uit. Dat scheelt weer een moeilijk omweg 👍

**Comment by lesteenman** [comment]
Mobiel kunnen wss beide menubalken gewoon onder elkaar in de lijst. Dan staan hogere prioriteit links nog steeds bovenaan.

**Comment by PauluzzS** [comment]
Dan desktop kan de overflow ook in een hamburger?

Groet,

Paul L. Smits

**Comment by lesteenman** [comment]
hamburger desktop = no.

Hier wel een indicatie hoe 2 menu balken er uit zou kunnen zien:

![mockup](https://user-images.githubusercontent.com/963290/30120230-8e75e29c-9328-11e7-8272-9794b7d08031.png)

**Comment by lesteenman** [comment]
Eerder stond dit trouwens beide in 1 balk, met verschillende fontsizes.

**Comment by PauluzzS** [comment]
prima mockup, maar die balk mag wat dunner en de tekst wat kleiner :P, het is nu groter dan de balk die zogenaamd belangrijker is.

**Comment by jpingen** [comment]
+1, zoiets had ik ook in gedachten. Rode balk mag wel iets dunner ja.

**Comment by lesteenman** [comment]
Voor de voorpagina; Dezelfde balk (dus kleiner en bovenin) of de balk zoals hij nu staat (onder de header image)?

**Comment by jpingen** [comment]
Onder de header image.

**Comment by PauluzzS** [comment]
prima onder de header image, als er maar van andere paginae ook te
navigeren is naar items in de rode balk

Groet,

Paul L. Smits

**Comment by lesteenman** [comment]
Ok, een eerste poging staat live.

**Comment by PauluzzS** [comment]
Nice. Ik vind het er al aardig uitzien. 
Echter de verdeling van elementen voelt nog onlogisch aan. Ik zou verwachten dat in het rode menu het intranet zit en in het witte menu de publieke shit zoals reizen. Dit omdat bij een hoger menu ik het idee heb hoger in een boom te gaan, of naar verwante externe sites. (Maar misschien ben ik nog te 1.0 hiervoor)

Sent from my Windows 10 phone

**Comment by lesteenman** [comment]
Ik ben zelf ook nog geen groot fan van de verdeling.

Issue om rekening mee te houden is dat het mobiele menu gewoon beide menu's
na elkaar zijn. Op zich, als de rode balk 'intranet' heeft en de witte balk
niet verandert na login (behalve login -> logout vervangen), zouden die
links onderaan gezet kunnen worden.

**Comment by jpingen** [comment]
Klinkt als een logische verdeling ja. Misschien op mobiel dan nog een
subtiele scheidingslijn tussen de twee sets menu's.

**Comment by lesteenman** [comment]
Alright, verdeling is aangepast.

**Comment by lesteenman** [comment]
Fix de uitlijning (beide menu's met de rechterrand van de content).

**Comment by PauluzzS** [comment]
Moet zeggen dat ik het menu op mobiel nu wat onduidelijk vind. Niets hint erop dat ik kan scrollen in het menu, behalve dat ik zelf m'n logout-optie zoek.
![photo_2017-09-08_22-08-56](https://user-images.githubusercontent.com/15788026/30229469-584b62da-94e2-11e7-9b57-3870fa25da7c.jpg)

**Comment by jpingen** [comment]
Mee eens. @lesteenman kan het mobiele menu niet de gehele lengte innemen? Of een duidelijke scrollbalk toevoegen :)

**Comment by PauluzzS** [comment]
Twee kolommen mag ook.... of is dat _not done_?

**Comment by lesteenman** [comment]
Da's not done idd. Was al aan het nadenken over manieren om scrollbaarheid
aan te geven (bijv shadow onderin en zorgen dat een van de items half te
zien is), maar wilde eerst afwachten of 't mensen überhaupt stoorde. Ja dus
:p

**Comment by lesteenman** [comment]
Overigens is dat vooral _not done_ omdat er sowieso telefoons zijn die nog smaller zijn, waardoor het niet past. Plus, je kunt best een keer een langer menu item krijgen.

**Comment by lesteenman** [comment]
![capture](https://user-images.githubusercontent.com/963290/30238943-e6b3a536-9551-11e7-846c-3645fc1e4ac4.PNG) Hopelijk helpt dit al wat.

**Comment by lesteenman** [comment]
Ik denk wel dat de tweede menubalk ook bovenin moet blijven hangen, samen met de eerste. Meningen?

**Comment by PauluzzS** [comment]
Ik heb wel gemerkt dat bij het navigeren in het 'intranet' op desktop het
vervelend kan zijn om weer naar boven te moeten scrollen.. Eeensch

Edoch hebben we de mening van de designer nodig​ @jpingen.

**Comment by jpingen** [comment]
Ja, is wel chill om die ook boven te laten plakken. :)

Mocht je bang zijn dat je dan teveel hoogte opvult, kun je m laten verwijnen als je naar beneden scrollt en laten verschijnen zodra je weer omhoog scrollt (zoals de url bar op mobiel).

**Comment by lesteenman** [comment]
Als het goed is blijft ie nu ook in beeld.

**Comment by PauluzzS** [comment]
Behalve op de homepage..
also, het idee van Pingen (laten verwijnen als je naar beneden scrollt en laten verschijnen zodra je weer omhoog scrollt) was niet haalbaar/mogelijk? (Van mij hoeft het niet, mijn schermen zijn groot genoeg)

**Comment by lesteenman** [comment]
Dat wel, maar wel meer moeite om goed te krijgen. Ik heb er zelf ook nog
geen last van gehad, dus nog niet de tijd voor genomen.
