### ISSUE TITLE
Tijd in activiteitenoverzicht fixen

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#35]
is nu -2 uur + 9 minuten for some reason

**Comment by lesteenman** [comment]
Huh, the fuck. Geloof echter dat dit bij de migratie mis is gegaan somehow. Als je nu een activiteit aanpast klopt het daarna wel. Dat is niet echt meer te fixen vrees ik...

**Comment by lesteenman** [comment]
De issue was dat het renderen van de date gebeurde door de al geformatteerde date door een strtotime te gooien, waarna de timezone fucked-up was, en dat weer te proberen te renderen. De rendering van de date is nu niet zoals ik 'm zou willen, maar dat moet anders opgelost worden. Bijvoorbeeld zo: http://www.drupalcontrib.org/api/drupal/contributions%21date%21date.theme/function/template_preprocess_date_display_range/7
