### ISSUE TITLE
Navigatie uitlijnen met content

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#39]
Aan de linker- of rechterkant van de container, nu in t midden oogt nogal rommelig zeker aangezien de 2e nav wel links is uitgelijnd.

**Comment by jpingen** [comment]
Nog niet gefixt!

**Comment by lesteenman** [comment]
Ah, had dit bij een andere issue gecombineerd (#34). Was vergeten dat er nog een losse was!

**Comment by lesteenman** [comment]
![capture](https://user-images.githubusercontent.com/963290/30238950-06a7ee56-9552-11e7-833c-dc990aaf0f72.PNG)
