### ISSUE TITLE
Foto's festival eindfeest naar eigen flickr kopieren

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#44]
Vanaf de AEGEE site? Wel mooi om die zelf ook te hebben.

**Comment by jpingen** [comment]
Indien ingelogd bij AEGEE: https://www.aegee-enschede.nl/photos/6

**Comment by lesteenman** [comment]
Wordt via COT gefixt dat we ze allemaal in full-res krijgen.
