### ISSUE TITLE
Wanneer uitgelogd: op homepage 'Recent' veranderen naar 'Nieuws'

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#45]

**Comment by lesteenman** [comment]
Hoewel ik 'recent' nog wel een betere titel vindt wanneer ingelogd (open for discussion), zie ik zo gauw geen makkelijke manier om dit aan te laten passen. Ik zet het op de iets langere termijn en pas het aan naar 'nieuws'.
