### ISSUE TITLE
Meer padding boven/onder main content

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#46]
Het witte vlak bij Geschiedenis, Nieuws, etc.. Staat de titel bovenaan lelijk dicht op de rand, en soms de content onderaan ook.

**Comment by PauluzzS** [comment]
Bij twijfel altijd minder padding

Groet,

Paul L. Smits

2017-09-06 20:35 GMT+02:00 jpingen <notifications@github.com>:

**Comment by jpingen** [comment]
Voor jou een Smits modus dan:

* {
padding:0!important;
margin:0!important;
}

**Comment by lesteenman** [comment]
Deze versie van de site krijgt geen smits-mode

**Comment by lesteenman** [comment]
@jpingen over welke pagina's heb je het nu? https://pcsa-incognito.nl/geschiedenis en dergelijke, dus in het algemeen de titel? Of op de voorpagina?
