### ISSUE TITLE
Fix country after migration

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#50]
Alle landen zijn op nederland gezet. Zo woonde ik in Brussel, Nederland en woon Kjell nu in Kobenhavn, Netherlands

**Comment by jpingen** [comment]
Gewoon annexeren die handel, opgelost.

**Comment by lesteenman** [comment]
Ik geloof niet dat landen ingevuld waren op de oude website. Kan het zo gauw in ieder geval niet terugvinden in de oude database.
