### ISSUE TITLE
Adres als locatie weergeven wanneer locatie niet bij Heer is

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#51]
Wanneer adres wordt ingevoerd en geen Heer wordt geselecteerd, wordt de locatie van een activiteit nog steeds als onbekend weergegeven.
Zou natuurlijk het adres moeten zijn.

**Comment by lesteenman** [comment]
Bij welke activiteit is dit atm het geval?
