### ISSUE TITLE
Theme color toevoegen

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#52]
Zie: https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/#meta_theme_color_for_chrome_and_opera

**Comment by lesteenman** [comment]
Hm, dacht dat ik dat al had. Moment.

**Comment by lesteenman** [comment]
Ok, zit er inderdaad al in, maar er lijkt een andere module te zijn die de mooie rode theme color override.

**Comment by jpingen** [comment]
Chrome (v 60.0.3112.116) op Android (v 7.0) op Moto G5 Plus. Werkt op andere sites (zoals hier op github) wel gewoon.

**Comment by lesteenman** [comment]
Yes, ik zie nu inderdaad ook dat het niet werkt op m'n telefoon. Dat wordt even wat meer uitzoekwerk waar de andere tag vandaan komt. Omdat er 2 theme-color tags in staan (1 zwart, 1 donkerrood) besluit ie denk ik om er maar geen van te pakken.
