### ISSUE TITLE
Polls publiek?

### ISSUE THREAD

**Issue by lesteenman** [lesteenman/pcsa-drupal-theme#54]
Momenteel zijn polls blijkbaar publiek zichtbaar. Willen we dit afschermen? Ik denk zelf van wel, gezien de onzin-dingen die er nog wel eens in langs komen. Eventueel is het een optie om de keuze te geven of het publiek moet zijn of niet, maar ik kan me zo gauw geen reden bedenken waarom je een publiek zichtbare poll zou willen.

**Comment by jpingen** [comment]
Afschermen gaarne!

**Comment by lesteenman** [comment]
Mooi, dat is al 2/3 actieve Github gebruikers.
