### ISSUE TITLE
Grotere foto's op praesidium pagina

### ISSUE THREAD

**Issue by lesteenman** [lesteenman/pcsa-drupal-theme#59]
Waarschijnlijk zijn hier imagecache(_external) modules voor nodig, om custom groottes te gebruiken. Nu is het of deze kleine, of te grote.

**Comment by PauluzzS** [comment]
gewoon lomp groot de praes in beeld doen dan

Groet,

Paul L. Smits

2017-09-08 9:46 GMT+02:00 Erik <notifications@github.com>:

**Comment by lesteenman** [comment]
![screenshot from 2017-09-08 15-51-05](https://user-images.githubusercontent.com/963290/30214670-90770810-94ad-11e7-8cf0-56e47b92f986.png)

**Comment by lesteenman** [comment]
Also, meer van de pagina opmaak jatten van https://www.jellepingen.com/pcsa/praesidium.html

**Comment by PauluzzS** [comment]
Juist!

Groet,

Paul L. Smits
