### ISSUE TITLE
Remove comment titles

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#60]
Zie: https://pcsa-incognito.nl/node/22634
 ![image](https://user-images.githubusercontent.com/16253465/30220338-5795986a-94bf-11e7-9224-89c937964a5c.png)

**Comment by jpingen** [comment]
Oh, en het woordje 'new'  mag wmb ook wel weg, danwel als klein label ergens naast de comment zelf. Op het moment is het nogal euh... gek.
![image](https://user-images.githubusercontent.com/16253465/30220469-cc99fa7a-94bf-11e7-8af7-363e80cd23eb.png)

**Comment by lesteenman** [comment]
Duplicate van #25. Titel van de issue net aangepast om duidelijker aan te geven waar het om gaat.
