### ISSUE TITLE
Menu blijft lelijk op home bij scrollen

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#62]
Something broke...
![image](https://user-images.githubusercontent.com/15788026/30235183-cd16e18e-9505-11e7-8cba-9f24f83dddda.png)

was it https://github.com/lesteenman/pcsa-drupal-theme/commit/ce3c4a690af77087d428e9042d0678387b4c3dd7 ?

**Comment by lesteenman** [comment]
Probably, yes. Waar gebeurt dat? Gewoon een activiteiten pagina?

**Comment by PauluzzS** [comment]
Op homepage only

Sent from my Windows 10 phone

**Comment by lesteenman** [comment]
Browser?

**Comment by PauluzzS** [comment]
Opera 47
Edge 40
