### ISSUE TITLE
garamond mogelijk te slechte x-height voor dit soort mini-titeltjes

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#67]
Zijn ze kleiner geworden of is het lettertype veranderd?
![image](https://user-images.githubusercontent.com/15788026/30241775-6d6eadfe-958a-11e7-993c-3aa4322ebc36.png)

**Comment by PauluzzS** [comment]
Door lage x-height worden gaten in letters dichtgedrukt op slechte schermen en lijkt het lettertype kleiner dan het is. Wellicht nog iets groter of ander lettertype overwegen.

**Comment by lesteenman** [comment]
Ah, dat is mee gegaan met een andere patch idd. Die pagina moet sowieso nog
iets beter.

**Comment by PauluzzS** [comment]
Nu zijn titels giganteusch en inconsistent. 
![image](https://user-images.githubusercontent.com/15788026/30250832-9c5ae792-9655-11e7-8909-d4c378cf03c5.png)

**Comment by lesteenman** [comment]
Foutje, da's wel foeilelijk idd.
