### ISSUE TITLE
Leugens over <a> tags

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#68]
It is said that 
> Allowed HTML tags: `<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd> <img> <p> <br>`

The first tag, however, may be allowed, but doesn't work:
![image](https://user-images.githubusercontent.com/15788026/30244662-d309e722-95c2-11e7-871e-5037769b3855.png)

**Comment by lesteenman** [comment]
Volgens mij zijn alle HTML tags nu toegestaan.

**Comment by PauluzzS** [comment]
Leugens

**Comment by lesteenman** [comment]
Waar gaat het mis? De vorige keer kwam het uiteindelijk doordat hij de '<' als html karakter parste ipv gewoon dat karakter te houden.

**Comment by lesteenman** [comment]
De editor is even gedisabled, aangezien deze module bagger werkt. Ik ga op zoek naar een betere. In de tussentijd kun je gewoon HTML typen in dat vak.
