### ISSUE TITLE
profielfoto ontbreekt bij reply draft

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#71]
Terwijl er wel ruimte voor lijkt te zijn:
![image](https://user-images.githubusercontent.com/15788026/30251012-236b5684-9658-11e7-905b-bf87eb8c27f1.png)

**Comment by lesteenman** [comment]
Wat je daar ziet is de preview van de draft?

**Comment by jpingen** [comment]
Als je repliet (repliedt? replyt?) op een andere comment, ontbreekt de profielfoto ook bij de parent comment

**Comment by PauluzzS** [comment]
Nee het is de draft, en de foto ontbreekt bij de parent. Preview wist ik
niet eens dat dat bestond.

Groet,

Paul L. Smits

**Comment by lesteenman** [comment]
Zal zo een blik werpen, had dat nog niet eens bekeken/getest.

**Comment by lesteenman** [comment]
Blijkbaar wordt de auteur niet meegegeven aan de template render. Ik weet zo gauw niet zeker hoe dat gefixt kan worden, maar vind de prioriteit lager dan bijv. #13, dus ik verplaats 'm naar 'first feature set'.
