### ISSUE TITLE
Inconsistente homepage wel/niet-ingelogd

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#72]
Styling van de homepage is inconsistent tussen wel of niet ingelogd zijn. Is niet echt een issue, maar ik vind de niet-ingelogd versie met kleinere, rode titels mooier. Ter vergelijking:

![image](https://user-images.githubusercontent.com/16253465/30251709-c8f54166-9665-11e7-94fc-82cfee9ed1c2.png)

**Comment by lesteenman** [comment]
Die issue is volgens mij nu ook gefixt met 8fe5676930220fd2702a2c8e178d21d74ad97692.
