### ISSUE TITLE
Datum format bij aanmaken activiteit

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#76]
Bij het aanmaken van een activiteit staat de datum in amerikaans format (mm/dd/yy) waar wij natuurlijk het logische dd/mm/yy hanteren.

Zie bijvoorbeeld:
![image](https://user-images.githubusercontent.com/16253465/30292307-ef146d1a-9735-11e7-9381-4531359b8d72.png)

**Comment by lesteenman** [comment]
Goed punt, daar wilde ik überhaupt nog een fatsoenlijke input method aan
hangen met een echte date picker.

**Comment by jpingen** [comment]
Ja date picker is wel chill :)

**Comment by PauluzzS** [comment]
Zou fijn zijn.

Groet,

Paul L. Smits

**Comment by Maharball1** [comment]
Niet alleen bij activiteiten. Ook bij nieuwsberichten en waarschijnlijk forumposts wordt de Amerikaanse stijl gehanteerd. Dus graag in de Drupal settings de datumnotatie wijzigen! @jpingen @lesteenman @PauluzzS

**Comment by lesteenman** [comment]
Dat gaat vooral om de display die gebruikt wordt op de verschillende pagina's, niet om de input method. Dat zijn in principe 2 losstaande issues die los van elkaar opgelost gaan worden, dus 2 losse issues.

**Comment by lesteenman** [comment]
Format is iig aangepast. Note to self voor de datepicker: https://www.drupal.org/node/1403654
