### ISSUE TITLE
Locatie activiteit ook zonder adres ingeven

### ISSUE THREAD

**Issue by jpingen** [lesteenman/pcsa-drupal-theme#77]
Bij het aanmaken van een activiteit en het invoeren van de locatie, kan je kiezen uit óf bij een Heer thuis, óf een adres invoeren (waarbij eerst een land gekozen moet worden). Ik wilde alleen Asterion typen, maar dat ging dus niet :p

**Comment by PauluzzS** [comment]
Ik vond het ALVreten en de ALV erop zetten ook al hel, omdat adres vereist
was :P

Groet,

Paul L. Smits

2017-09-11 21:14 GMT+02:00 jpingen <notifications@github.com>:

**Comment by lesteenman** [comment]
Hmm, bijzonder. Ik had aangevinkt dat elk veld optioneel was, leek me genoeg :P

**Comment by lesteenman** [comment]
Ik kan trouwens het ALVreten gewoon aanpassen met alleen 'Vrijhof' op regel 1... Waar gaat het mis?

**Comment by lesteenman** [comment]
![capture](https://user-images.githubusercontent.com/963290/30296541-cde2a6fc-9744-11e7-9c0d-f4f6687e00be.PNG)
Ok, land uitzetten kan, maar dat wordt gebruikt om het formaat van het adresveld te bedenken. Zonder land ziet het er uit als op de screenshot, waarbij de eerste regel wordt gebruikt in de teaser op de activiteiten pagina.

Zelf vind ik het 'echte' adresform eigenlijk wel fijn, maar dan moet een default van 'netherlands' zonder dat dit meteen bij de activiteit komt te staan als de locatie (wat nu het geval is) wel mogelijk zijn. Meningen?

**Comment by jpingen** [comment]
Ja, default Nederland aanzetten en gewoon niet laten zien? Enige keer dat dat niet klopt is waarschijnlijk bij een MR ofzo.. ("Hamburg, Netherlands"). Of gewoon één regel waar je zelf wat kan typen (ipv 5 zoals hierboven), ging voorheen ook altijd goed. Echt adres kan je indien noodzakelijk nog in de omschrijving gooien ofzo
