### ISSUE TITLE
Allow additional photos for dispuutsobjecten

### ISSUE THREAD

**Issue by PauluzzS** [lesteenman/pcsa-drupal-theme#82]
Een voor en achterkant, een foto met de maker, een foto in huidige staat etc. Meer visueel is leuker.

(genoemde foto's zijn slechts voorbeelden, ik zou hier de gebruikers vrijheid in geven)

**Comment by lesteenman** [comment]
Aangepast, je kunt nu meerdere foto's uploaden. Kun je kijken of de manier hoe dat nu werkt fijn werkt?

**Comment by PauluzzS** [comment]
Werkt op zich wel, maar is nog niet heel fraai. (zie gestolen meter)
Wellicht nog eens naar kijken als ook #66 getackeld is

**Comment by lesteenman** [comment]
Ah, da's niet fraai nee. Het kan echter vooral wat styling gebruiken in z'n
algemeen. @jpingen? Ik heb ook speciaal een tag gemaakt voor issues waar
creatieve input nodig is.

**Comment by jpingen** [comment]
Prima, die input komt over een week of 2 :)
