### ISSUE TITLE
Reload error

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#83]
![image](https://user-images.githubusercontent.com/30278588/30382367-3784f956-989f-11e7-9762-fc6c27693e35.png)

Tijdens het herladen van de site, kreeg ik de volgende fout. Na nogmaals herladen deed de site het wel.

**Comment by lesteenman** [comment]
Wacht, wanneer heb je deze voor het laatst gehad? Toen je mij er over appte?

**Comment by Maharball1** [comment]
Ja. En zag dat Smits hem ook al eerder had.

**Comment by lesteenman** [comment]
Vlak daarna heb ik swap geheugen toegevoegd aan de server, waardoor dit niet meer voor zou moeten komen, als ik de gok over de oorzaak goed had (_fingers crossed_). Als dat daarna nog voorkomt hoor ik het graag, anders sluit ik dit over +- 72 uur.
