### ISSUE TITLE
Expliciet 'onbekend' flag voor activiteiten

### ISSUE THREAD

**Issue by lesteenman** [lesteenman/pcsa-drupal-theme#85]
Afwezigheid van enige flag kan niet meer als 'onbekend' gelden, omdat we dan niet weten of je al geantwoord hebt.

Bonus: X uur (24? 72?) voor de activiteit wel verplichten om een aanwezigheid aan te geven.

**Comment by PauluzzS** [comment]
Het werkt niet goed. Ik heb me onbekend gezet voor een activiteit over 6 dagen, maar ik moet me nu op aanwezig of afwezig zetten om de site verder te zien:
![image](https://user-images.githubusercontent.com/15788026/30773207-3d3e6f24-a06c-11e7-803a-c1bb98f39e4c.png)
- Er staat bij dat het binnen 48 uur is, maar dat is een leugen.
- Er staat boven dat "Sinds uw vorige bezoek zijn er een aantal nieuwe activiteiten geplaatst, waarvoor we moeten weten of u aanwezig bent." Dit is ook een leugen, ik heb me immers zelf op onbekend gezet. deze tekst zou niet moeten verschijnen als het om 48-uurs-units gaat.

**Comment by lesteenman** [comment]
Meh, het tweede punt is niet per se relevant imo, vooral omdat het een
combinatie kan zijn. Dat je nu al verplicht aan moet geven of je er bij
bent is wel een bug.

**Comment by PauluzzS** [comment]
> Sinds uw vorige bezoek is er een aantal nieuwe activiteiten geplaatst en/of er zijn binnen 48 uur activiteiten waarvoor u op onbekend staat, waarvoor we moeten weten of u aanwezig bent.

**Comment by lesteenman** [comment]
Aangezien voor deze bug nu een specifieke issue voor is (#121), sluit ik deze.
