### ISSUE TITLE
Kopje 'nieuws' op voorpaginafeed onduidelijk

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#86]
Bij nieuws denk ik aan nieuwsberichten en niet een feed met forumposts, polls, nieuwsberichten etcetera. Wellicht hernoemen naar iets als: Recente activiteiten

**Comment by lesteenman** [comment]
Alleen voor ingelogde users. Anoniem kan nog steeds 'nieuws'.

**Comment by PauluzzS** [comment]
Recente activiteiten is net zo dubieus.

Groet,

Paul L. Smits

**Comment by lesteenman** [comment]
Huh. Hier had ik ook al meer op gereageerd dacht ik. Recente activiteiten is inderdaad ook twijfelachtig, en ik had in eerste instantie dacht ik ook juist 'recent' omdat alle andere dingen dubieus leken. Voor niet ingelogde users is 'Nieuws' nog wel een nuttig kopje.
