### ISSUE TITLE
Formatting in WYSIWYG editor is inconsistent met resultaat

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#87]
Bij het maken van een activiteit kan men tekst toevoegen in de editor. Dit zag er in dit geval uit zoals bij afbeelding 1. De weergave is zoals in afbeelding 2. De formatting klopt niet en geeft in dit geval ernstige virtuele AIDS.
![image](https://user-images.githubusercontent.com/30278588/30383134-3e6762fc-98a1-11e7-93c7-0612b0fdbdb9.png)
![image](https://user-images.githubusercontent.com/30278588/30383166-5abc0548-98a1-11e7-80e1-517fbc39b184.png)

**Comment by lesteenman** [comment]
Bedoel je 'inconsistentie' met 'visuele aids'?

**Comment by Maharball1** [comment]
De opmaak in de editor is niet gelijk aan de opmaak op de site.

**Comment by lesteenman** [comment]
Check, inconsistentie dus. Valid point!

**Comment by jpingen** [comment]
Al ben ik in dit geval wel voorstander van de opmaak in nieuwsberichten en activiteit-omschrijvingen te limiteren, juist om visuele aids te voorkomen.

**Comment by Maharball1** [comment]
Prima, maar inconstistent. Hoe het consistent wordt gemaakt, maakt niet uit.

**Comment by lesteenman** [comment]
> Al ben ik in dit geval wel voorstander van de opmaak in nieuwsberichten en activiteit-omschrijvingen te limiteren, juist om visuele aids te voorkomen.

Hmm, erg goed punt. Aangezien alle HTML tags toestaan toch niet hielp om #68 te verhelpen, ga ik weer over naar een limited set waar de headers die elders op de pagina gebruikt worden niet toegestaan worden.

**Comment by PauluzzS** [comment]
Ja, we moeten niet doen alsof het een rich text editor is als dat
vervolgens allemaal gestript wordt.

Groet,

Paul L. Smits

**Comment by PauluzzS** [comment]
Ik zou denk ik 1 type header voor binnen posts toestaan. Alsook ULs en OLs
voor lijsten. Daarmee kun je al een hoop aan opmaak, zonder aids.

Groet,

Paul L. Smits

2017-09-13 17:04 GMT+02:00 Erik <notifications@github.com>:

**Comment by lesteenman** [comment]
H3 wilde ik toestaan (als die niet al gebruikt wordt, anders h4). Lists
miste ik ook al, maar dat ligt aan de editor an sich, wat iets lastiger is
om te vervangen. Je kunt al wel ul, ol en li gebruiken, geloof ik.

**Comment by lesteenman** [comment]
Tja, als je vanuit Word gaat pasten kan er wel eens iets mis gaan...

Ik heb nu een nieuwe editor aan gezet (CKEditor), die als het goed is wel fatsoenlijk werkt. Die haalt, als het goed is, ook niet-toegestane opmaak uit content die van Word af komt.

**Comment by Maharball1** [comment]
De tekst in de editor en het eindresultaat komt meer overeen nu ja.

Op 14 september 2017 om 12:39 schreef Erik <notifications@github.com>:

**Comment by PauluzzS** [comment]
![image](https://user-images.githubusercontent.com/15788026/30505745-f04218c4-9a76-11e7-9e56-1022bec3673a.png)
De nieuwe editor doet niet aan automatisch websites omzetten naar links?

**Comment by Maharball1** [comment]
+1 voor wel!

Op 16 sep. 2017 00:35 schreef "Paul S" <notifications@github.com>:

**Comment by lesteenman** [comment]
Dat het wel werkt of je dat wilt?

**Comment by Maharball1** [comment]
Dat het automatisch een link wordt

Op 16 sep. 2017 01:22 schreef "Erik" <notifications@github.com>:

> Dat het wel werkt of je dat wilt?
>

**Comment by lesteenman** [comment]
... Dus dat je dat wilt, of dat het al werkt.
