### ISSUE TITLE
Geen indicatie langer nieuwsbericht

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#88]
Zoals in de afbeelding te zien is lijkt het alsof dit het gehele nieuwsbericht is. Mocht er ooit wel een 1-regelig nieuwbericht komen, dan denkt met dat het niet alles zou kunnen zijn. Op een of andere manier duidelijk maken dat dit nog niet het gehele nieuwsbericht is. Die Read more lost dit niet op, want daarop zou alleen kunnen klikken als men een comment wil plaatsen.

![image](https://user-images.githubusercontent.com/30278588/30383493-1aa83994-98a2-11e7-9bf5-0220e713aba4.png)

**Comment by lesteenman** [comment]
Idee: truncaten aan het eind van het echte bericht. Het resultaat zou in dit geval worden: `geschorts wegens discimi...`, of iets soortgelijks.
