### ISSUE TITLE
Ontbreken Home-button

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#90]
Na het inloggen heb je een mooie acitivityfeed. Nadat je naar een andere pagina bent gegaan is de enige mogelijkheid om terug te keren naar die activityfeed door terug te gaan naar pcsa.nl of linksboven op de tekst te klikken, wat niet alle Heeren door zullen hebben terwijl het wel een mooi overzicht is. Zou er graag naar terugkeren om de andere recente activiteiten te zien.

**Comment by lesteenman** [comment]
Hm, voor mijzelf is dat een heel standaard manier om terug te gaan naar 'home'. Hier zou eventueel een expliciete 'home' knop voor in het menu gezet kunnen worden, was ik al eerder aan het overwegen.

**Comment by jpingen** [comment]
Ik vond zelf het logo linksboven ook wel logisch genoeg, en alles wat daar staat vind je ook onder activiteiten/nieuws, toch?

**Comment by Maharball1** [comment]
@jpingen Nee, er staan ook polls en forumtopics in die feed. Voor het gebruiksgemak is het fijn om ook een knop in het menu te hebben om naar die feed te gaan.

**Comment by jpingen** [comment]
Subjectief, maar ok

**Comment by lesteenman** [comment]
Het is inderdaad wel meer dan normaal, aangezien het gewoon een feed is van
alle recente activiteit, verspreid over forums, nieuws, activiteiten, etc.
Alleen comments komen daar niet tussen.

**Comment by PauluzzS** [comment]
Ik ben tegen, kunt gewoon op pcsa klikken, of op vorige in je browser. Ook
als je dat niet gewend bent heb je dat na 2 keer de website gebruiken wel
door, en voor externen is het niet relevant.

Groet,

Paul L. Smits

2017-09-13 17:03 GMT+02:00 Erik <notifications@github.com>:

> Het is inderdaad wel meer dan normaal, aangezien het gewoon een feed is van
> alle recente activiteit, verspreid over forums, nieuws, activiteiten, etc.
> Alleen comments komen daar niet tussen.
>

**Comment by Maharball1** [comment]
We moeten ook aan mensen denken die minder in de IT thuis zijn of ouder
zijn dan 28.

Op 13 sep. 2017 23:38 schreef "Paul S" <notifications@github.com>:

> Ik ben tegen, kunt gewoon op pcsa klikken, of op vorige in je browser. Ook
> als je dat niet gewend bent heb je dat na 2 keer de website gebruiken wel
> door, en voor externen is het niet relevant.
>
> Groet,
>
> Paul L. Smits
>
> 2017-09-13 17:03 GMT+02:00 Erik <notifications@github.com>:
>
> > Het is inderdaad wel meer dan normaal, aangezien het gewoon een feed is
> van
> > alle recente activiteit, verspreid over forums, nieuws, activiteiten,
> etc.
> > Alleen comments komen daar niet tussen.
> >

**Comment by lesteenman** [comment]
Zou wel interessant zijn om te zien hoe veel mensen dit wel of niet door
hebben...

**Comment by PauluzzS** [comment]
Ze leren het maar.

**Comment by Maharball1** [comment]
Mm..please reopen?

**Comment by lesteenman** [comment]
Ik denk eigenlijk dat het een non-issue is...

**Comment by Maharball1** [comment]
Ja, prima. Dat is wat anders dan dat Smits wat vaag brabbelt en hem zomaar sluit.

**Comment by PauluzzS** [comment]
Neemt alleen maar ruimte in

Groet,

Paul L. Smits

**Comment by lesteenman** [comment]
https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page

**Comment by Maharball1** [comment]
Al is dit geen logo maar lelijke tekst op een mooie afbeelding :p

Op 14 sep. 2017 00:26 schreef "Erik" <notifications@github.com>:

> https://ux.stackexchange.com/questions/81727/why-is-it-
> standard-for-a-website-logo-to-navigate-to-the-home-page
>

**Comment by PauluzzS** [comment]
Het is alleen lelijke tekst op een mooie afbeelding als je al bent waar je
wilt zijn...

Groet,

Paul L. Smits

**Comment by lesteenman** [comment]
Dan moet er misschien een mooier logo dat daar goed past ;) wel mee eens
dat de tekst mooier kan.

Die link was daadwerkelijk nog wel interessant trouwens.

**Comment by PauluzzS** [comment]
Heb je de tekst nu grijs gemaakt?

Ik vond de rode tekst overal juist erg mooi. Zou het zeker rood houden
(zoals het was) wanneer die menubalk grijzig is.
Bij de transparante menubalk op de home screen zou ik ook geen grijs doen,
maar daar kan wel iets gebeuren om de tekst wat meer contrast te geven.

Groet,

Paul L. Smits

**Comment by lesteenman** [comment]
Nee, dat is al een tijdje een bugje die ik moet fixen..

**Comment by jpingen** [comment]
Er kan nog wel een maskertje naast oid, als de tekst te lelijk wordt bevonden.
