### ISSUE TITLE
Ontbreken informatie profiel

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#92]
Er zijn bij het profiel updaten opties (afbeelding 1) waarvan het resultaat niet wordt weergegeven in het profiel zelf (afbeelding 2), na het opslaan.
![image](https://user-images.githubusercontent.com/30278588/30384068-91c82484-98a3-11e7-99d6-9a5b405ed9b1.png)
![image](https://user-images.githubusercontent.com/30278588/30384100-ae8fc766-98a3-11e7-96ef-dc8afe755705.png)

**Comment by lesteenman** [comment]
Land is in principe overbodig, want dat zit ook in je adres, geloof ik. Die moet er denk ik gewoon uit.

**Comment by Maharball1** [comment]
Niet als iemand van een ander land afkomstig is. Dit gaat om je
geboorteland, niet adres.

Op 13 sep. 2017 22:47 schreef "Erik" <notifications@github.com>:

**Comment by lesteenman** [comment]
Ah, heb ik het daarom toegevoegd... Dit is echt te lang geleden. Beide zijn zichtbaar.

**Comment by PauluzzS** [comment]
Place a person is from is m.i. niet een land. Haal eens weg.
Ik heb daar bijvoorbeeld mijn geboorteplaats ingevuld, maar vind het tamelijk overbeaudig.

**Comment by Maharball1** [comment]
Ook prima, maar als het in de opties staat ook weergeven op profiel.

Op 14 sep. 2017 00:09 schreef "Paul S" <notifications@github.com>:

**Comment by PauluzzS** [comment]
Wat mij betreft halen we de hele 'place a person is from' dan weg. 
Ook interesses gebruiken we trouwens niet (mogen van mij dan ook weg...)

**Comment by lesteenman** [comment]
Ik heb geen sterke mening over geboorteplaats, maar denk dat het niet per
se heel interessant is. Benieuwd naar een doorslaggevende stem ;)

Interesses lijken me idd niet interessant.

**Comment by Maharball1** [comment]
Weghalen!

Op 14 sep. 2017 00:23 schreef "Erik" <notifications@github.com>:

> Ik heb geen sterke mening over geboorteplaats, maar denk dat het niet per
> se heel interessant is. Benieuwd naar een doorslaggevende stem ;)
>
> Interesses lijken me idd niet interessant.
>

**Comment by Maharball1** [comment]
Maar ook werkgever etcetera werkt niet, of occupation, of hie het ook heet.

Op 14 sep. 2017 00:25 schreef :

> Weghalen!
>
> Op 14 sep. 2017 00:23 schreef "Erik" <notifications@github.com>:
>
>> Ik heb geen sterke mening over geboorteplaats, maar denk dat het niet per
>> se heel interessant is. Benieuwd naar een doorslaggevende stem ;)
>>
>> Interesses lijken me idd niet interessant.
>>

**Comment by lesteenman** [comment]
Occupation vond ik daadwerkelijk nog wel wat toevoegen aan je werkgever.
