### ISSUE TITLE
Bij toevoegen eigen adres mist spatie

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#94]
Zie foto 1 en weergave in foto 2. Mist een spatie.
![image](https://user-images.githubusercontent.com/30278588/30384470-a832ecee-98a4-11e7-9aa7-3b2bc318cc1a.png)
![image](https://user-images.githubusercontent.com/30278588/30384490-b4c82dfc-98a4-11e7-9f62-4aab8a4dfadd.png)

**Comment by lesteenman** [comment]
Hmm, kak. Dit had eigenlijk al terug gezet moeten worden naar ander datum format (zie #77). Hopelijk is dat nog aan te passen zonder dat de extra velden verdwijnen.

**Comment by lesteenman** [comment]
@Maharball1 bij welke activiteit was dit? Het adres formaat is aangepast (het is weer country-specific), dus als het goed is wordt alles nu gerendered. Ik wil alleen even kijken of het overzetten naar nieuwe adres-format automatisch goed is gegaan.

**Comment by Maharball1** [comment]
Was bij Colloquium Awakimjan, het ziet er volgens mij nu beter uit, check
zelf maar.

2017-09-14 11:09 GMT+02:00 Erik <notifications@github.com>:

**Comment by lesteenman** [comment]
Top!
