### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#98]
Ik wil graag weer emoticons terug zien op de site, zodat ik die in commentaren, posts of op andere manier kan gebruiken.

**Comment by lesteenman** [comment]
Zolang je een keyboard hebt die het ondersteund werken ze prima hoor ;) Zal kijken, maar weet niet of dat met de editor die we nu hebben mogelijk is. Zo nee, dan is het een stuk meer werk om het te vervangen met een nieuwe editor en wordt het misschien wat meer opgeschoven.

In de tussentijd kun je emoji hiervandaan kopieren: http://getemoji.com

**Comment by Maharball1** [comment]
Top! Dus ze werken wel, alleen niet in de hudige editor zichtbaar?

**Comment by lesteenman** [comment]
Ja, Emoji zijn gewoon karakters als elke letter. Vanaf je telefoon kun je
al helemaal makkelijk Emoji gebruiken met een toetsenbord.

**Comment by PauluzzS** [comment]
Nee, gebruik je gewoon je touch keyboard op Windows 10, mafkees! Eventueel kun je de volgende uitleg onder het tekstvak zetten:
Rechtermuisknop op je taakbalk -> "show touch keyboard button" aanvinken. Nu kun je in je systeemvak het toetsenbord aanklikken en emoji's gebruiken zoals in al uw andere apps. 👌

**Comment by PauluzzS** [comment]
Dus geen vermelding hoe desktopgebruikers dit kunnen doen, ter Leeringh ende Vermaeck van de windowsgebruikende digibeten onder de Heeren?

**Comment by lesteenman** [comment]
Hm, daar kan ik evt. nog een keer naar kijken. Dan moet ik echter wel die module van het tekstvak gaan aanpassen... Matig.
