### ISSUE TITLE
Forum: visuele AIDS

### ISSUE THREAD

**Issue by Maharball1** [lesteenman/pcsa-drupal-theme#99]
Ik denk dat het forum wat CSS nodig heeft. Ik vind dit er niet zo prettig en uitnodigd uitzien: 
![image](https://user-images.githubusercontent.com/30278588/30385409-53cfce62-98a7-11e7-8854-c00a34b34944.png)
![image](https://user-images.githubusercontent.com/30278588/30385451-8255d164-98a7-11e7-97a8-6c8965068ced.png)

**Comment by jpingen** [comment]
Check eerst even de overige issues: #9
